---
- name: Block outgoing HTTP and HTTPS traffic
  hosts: centos
  become: yes

  tasks:
    - name: Install iptables-services
      yum:
        name: iptables-services
        state: present

    - name: Save iptables rules
      shell: iptables-save > /etc/sysconfig/iptables

    - name: Block outgoing HTTP traffic
      iptables:
        table: filter
        chain: OUTPUT
        protocol: tcp
        destination_port: 80
        jump: DROP
        state: present

    - name: Block outgoing HTTPS traffic
      iptables:
        table: filter
        chain: OUTPUT
        protocol: tcp
        destination_port: 443
        jump: DROP
        state: present

    - name: Start iptables service
      service:
        name: iptables
        state: started
        enabled: yes
