---
- name: Get disk label and create a mount point
  hosts: all
  become: yes
  tasks:
    - name: Gather disk facts
      command: lsblk -o NAME,TYPE,SIZE,UUID,MOUNTPOINT -dn
      register: lsblk_output

    - name: Debug lsblk output
      debug:
        var: lsblk_output.stdout_lines

    - name: Find non-main disk
      set_fact:
        non_main_disk_info: "{{ item.split() }}"
      loop: "{{ lsblk_output.stdout_lines }}"
      loop_control:
        label: "{{ item }}"
      when:
        - item.split() | length >= 5
        - item.split()[1] == 'disk'
        - item.split()[0] != 'sda'
        - item.split()[4] == ''

    - name: Fail if no suitable non-main disk is found
      fail:
        msg: "No suitable non-main disk found."
      when: non_main_disk_info is not defined

    - name: Create filesystem on the non-main disk
      filesystem:
        fstype: ext4
        dev: "/dev/{{ non_main_disk_info[0] }}"
      when: non_main_disk_info is defined

    - name: Create mount point directory
      file:
        path: /mnt/my_mount_point
        state: directory

    - name: Mount the filesystem
      mount:
        path: /mnt/my_mount_point
        src: "/dev/{{ non_main_disk_info[0] }}"
        fstype: ext4
        state: mounted

    - name: Persist the mount in fstab
      mount:
        path: /mnt/my_mount_point
        src: "/dev/{{ non_main_disk_info[0] }}"
        fstype: ext4
        opts: defaults
        state: present
