---
- name: Create partition on new disk
  community.general.parted:
    device: "{{ new_disk }}"
    number: 1
    label: "gpt"
    flags: lvm
    state: present
    part_end: "100%"

- name: Set VG name
  set_fact:
    vgName: "{{ new_disk | basename }}vg"

- name: Create/Extend PV and VG
  community.general.lvg:
    vg: "{{ vgName }}"
    pvs: "{{ new_disk }}1"

- name: Register the volumes from Morpheus
  set_fact:
    volumes: "{{ morpheus['instance']['containers'][0]['server']['volumes'] }}"

- name: Get the name of the volume matching new_disk
  set_fact:
    volume_name_result: "{{ volumes | selectattr('deviceName', 'equalto', new_disk) | list }}"

- name: Extract volume name from the result
  set_fact:
    volume_name: "{{ volume_name_result[0].name }}"
  when: volume_name_result | length > 0

- name: Replace / with _ and set lv_name
  set_fact:
    lv_name: "{{ volume_name | replace('/', '_') }}"

- name: LV with 100% free space in vg
  community.general.lvol:
    vg: "{{ vgName }}"
    lv: "{{ lv_name }}"
    size: 100%FREE

- name: Format the lv with ext4
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/{{ vgName }}/{{ lv_name }}"

- name: Set mount path
  set_fact:
    mount_path: "/{{ volume_name | basename }}"

- name: Create target directory
  ansible.builtin.file:
    path: "{{ mount_path }}"
    state: directory
    mode: '0755'

- name: Mount the lv
  ansible.posix.mount:
    path: "{{ mount_path }}"
    src: "/dev/{{ vgName }}/{{ lv_name }}"
    fstype: ext4
    state: mounted

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/{{ vgName }}/{{ lv_name }}  {{ mount_path }}  ext4  defaults  0  0"
    create: yes
  become: true

- name: Remount all in fstab
  command: mount -a
  become: true
