---
- name: Update /etc/hosts file
  hosts: all
  become: yes
  tasks:
    - name: backup current /etc/hosts file
      copy:
        src: /etc/hosts
        dest: /etc/hosts.bak
        owner: root
        group: root
        mode: 0600
    - name: update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: '{{item}}'
      with_items:
        - '127.0.0.1 localhost'
        - '192.168.1.100 host1'
        - '192.168.1.101 host2'
