---
- name: Install LAMP Stack on Rocky Linux
  hosts: your_server_ip_or_hostname
  become: yes
  become_method: sudo
  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
      register: update_result

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache and enable it at boot
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install MySQL
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL and enable it at boot
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Secure MySQL Installation
      command: mysql_secure_installation
      args:
        stdin: |
          Y
          your_mysql_root_password
          your_mysql_root_password
          Y
          Y
          Y
          Y
      when: update_result.changed

    - name: Install PHP and required modules
      yum:
        name:
          - php
          - php-mysql
          - php-common
          - php-cli
          - php-json
          - php-opcache
          - php-readline
        state: present

    - name: Restart Apache to apply PHP changes
      service:
        name: httpd
        state: restarted
