- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: latest
        
    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install MySQL
      dnf:
        name:
          - mysql-server
          - mysql
        state: latest

    - name: Start MySQL
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install PHP
      dnf:
        name:
          - php
          - php-mysqlnd
        state: latest

    - name: Configure PHP
      lineinfile:
        path: /etc/php.ini
        regexp: '^date.timezone ='
        line: 'date.timezone = Europe/London'

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
