# Compare the disks in OS with Morpheus volumes list. Skip sda and verify if other disks are partitioned and mounted as per label
---
- name: Disk count in Morpheus
  debug:
    msg: "Total number of disks on instance in Morpheus {{ disk_list_count }}./n Skipping sda check..."

- name: Iterate through morpheus volumes and check mount points
  block:
    - name: Set the initial new_disk to null
      set_fact:
        new_disks_final: []

    - name: Check if mount point exists
      stat:
        path: "{{ item.name }}"
      register: mount_point_stat
      with_items: "{{ morpheus['instance']['containers'][0]['server']['volumes'] }}"
      when: item.deviceName != '/dev/sda'

    - name: Debug mount_point_stat
      debug:
        msg: "{{ mount_point_stat }}"

    - name: Set the new_disks fact if mount point does not exist
      set_fact:
        new_disks_final: "{{ new_disks_final + [item.item.deviceName | regex_replace('/dev/', '')] }}"
      when: "item.stat is defined and not item.stat.exists and item.item.deviceName != '/dev/sda'"
      with_items: "{{ mount_point_stat.results }}"

    - name: Debug final new_disks
      debug:
        var: new_disks_final

    - name: Include additional tasks if new_disks_final is defined
      include_tasks: new_disk.yml
      vars:
        new_disks: "{{ new_disks_final }}"
      when: new_disks_final | length > 0
  when: disk_list_count_int == disk_data_count_int
