# Setup the partition when a new disk is added during reconfigure.
---
- name: Scan for new disks
  become: true
  shell: echo "- - -" | sudo tee /sys/class/scsi_host/host*/scan >/dev/null

- name: Create partition
  community.general.parted:
    device: "/dev/{{ item }}"
    number: 1
    label: "gpt"
    flags: lvm
    state: present
    part_end: "100%"
  with_items: "{{ new_disks }}"

- name: Debug partitions
  command: lsblk /dev/{{ item }}1
  register: partitions
  with_items: "{{ new_disks }}"
  ignore_errors: yes

- name: Display partition info
  debug:
    msg: "Partition info: {{ partitions.stdout_lines }}"
  when: partitions is defined

- name: Set VG name
  set_fact:
    vgName: "vg_data"

- name: Create PV
  command: pvcreate /dev/{{ item }}1
  with_items: "{{ new_disks }}"

- name: Debug PV creation
  command: pvs
  register: pvs_info
  ignore_errors: yes

- name: Display PV info
  debug:
    msg: "PV info: {{ pvs_info.stdout_lines }}"
  when: pvs_info is defined

- name: Create VG
  lvg:
    vg: "{{ vgName }}"
    pvs: "/dev/{{ item }}1"
  with_items: "{{ new_disks }}"

- name: Debug VG creation
  command: vgs
  register: vgs_info
  ignore_errors: yes

- name: Display VG info
  debug:
    msg: "VG info: {{ vgs_info.stdout_lines }}"
  when: vgs_info is defined

- name: Create LV
  lvol:
    vg: "{{ vgName }}"
    lv: "{{ 'lv_' ~ item }}"
    size: "100%FREE"
  with_items: "{{ new_disks }}"

- name: Debug LV creation
  command: lvs
  register: lvs_info
  ignore_errors: yes

- name: Display LV info
  debug:
    msg: "LV info: {{ lvs_info.stdout_lines }}"
  when: lvs_info is defined

- name: Format the lv
  filesystem:
    fstype: ext4
    dev: "/dev/{{ vgName }}/{{ 'lv_' ~ item }}"
  with_items: "{{ new_disks }}"

- name: Target directory
  ansible.builtin.file:
    path: "/mnt/{{ 'lv_' ~ item }}"
    state: directory
    mode: "0755"
  with_items: "{{ new_disks }}"

- name: mount the lv
  ansible.posix.mount:
    path: "/mnt/{{ 'lv_' ~ item }}"
    src: "/dev/{{ vgName }}/{{ 'lv_' ~ item }}"
    fstype: ext4
    state: mounted
  with_items: "{{ new_disks }}"
